### Creating user juan_perez
POST http://localhost:8080/api/users
Content-Type: application/json
Accept: application/json

{
   "userName": "alexander-sosa"
}

### Creating user pedro_gomez
POST http://localhost:8080/api/users
Content-Type: application/json
Accept: application/json

{
"userName": "pedro_gomez"
}

### Creating user maria_avila
POST http://localhost:8080/api/users
Content-Type: application/json
Accept: application/json

{
  "userName": "maria_avila"
}

### Creating a tweet
POST http://localhost:8080/api/tweet
Content-Type: application/json
Accept: application/json

{
  "userId": 1,
  "tweetText": "probando de nuevo mmgv x2"
}

### Following
POST http://localhost:8080/api/follows
Content-Type: application/json
Accept: application/json

{
  "userFollowerId": 4,
  "userFolloweeId": 1
}

### Getting timeline...
GET http://localhost:8080/api/users/timeline/2
Accept: application/json