### Creating user...
POST http://localhost:8080/api/users
Content-Type: application/json
Accept: application/json

{
   "userName": "alexander-sosa"
}

### Creating tweet...
POST http://localhost:8080/api/tweet
Content-Type: application/json
Accept: application/json

{
  "userId": 6,
  "tweetText": "probando desde el redis hdtpm 777"
}

### Following...
POST http://localhost:8080/api/follows
Content-Type: application/json
Accept: application/json

{
  "userFollowerId": 7,
  "userFolloweeId": 6
}

### Getting timeline...
GET http://localhost:8080/api/users/timeline/7
Accept: application/json