### Creating user...
POST http://localhost:8080/api/users
Content-Type: application/json
Accept: application/json

{
   "userName": "alexander-sosa"
}

### Creating tweet...
POST http://localhost:8080/api/tweet
Content-Type: application/json
Accept: application/json

{
  "userId": 1,
  "tweetText": "new tweet with redis down"
}

### Following...
POST http://localhost:8080/api/follows
Content-Type: application/json
Accept: application/json

{
  "userFollowerId": 2,
  "userFolloweeId": 1
}

### Getting timeline...
GET http://localhost:8080/api/users/timeline/2
Accept: application/json